version: "3.9"
services:
  db:
    image: mysql:8.4
    container_name: db
    restart: always
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    healthcheck:
      # healthcheck for checking the mysql container is up before starting my app container
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - '3307:3306'
    networks:
      - flask-net
  web:
    build: .
    image: flask-app-matzov
    container_name: app
    depends_on:
    # starting the container only after the mysql container is up and running
      db: 
        condition: service_healthy
    ports:
      - "5000:5000"
    networks:
      - flask-net 
    links:
      - db
    env_file:
      - .env

networks:
  flask-net:
    external: true
